### PR TITLE
Refactor docs and readme for Landr

### PR DESCRIPTION
**Pull request by andrewnhem**
This minor change refactors the readme, docs, and assets to conform to
Landr conventions.

No breaking changes were made to the application, but users will notice
a different with the documentation and readme experience.

Change-type: minor
Signed-off-by: Andrew Nhem <andrewn@balena.io>

### CODE REVIEW

**Comment by andrewnhem** [comment]
@balena-ci retest

**Comment by iamsolankiamit** [comment]
@andrewnhem Landr sites are not regenerated on retest, so this probably won't work. we either need to add new commits or create a new PR for landr to trigger again.

**Comment by andrewnhem** [comment]
Haha it looked dope for a moment... until that bug kicked in @iamsolankiamit . At least Landrbot is here now :D Thanks tho!

I'll revisit this once we get some more cleanup and "blockification" of the code. Saves me a round of work if I wait for blocks esp.

**Comment by maggie0002** [comment]
Appears to be docs for BalenaSound, not Cam

**Pull request closed without merging**
